apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: oficina-app
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
