apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oficina-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: oficina-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /oficina/prod/app
        property: JWT_SECRET
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /oficina/prod/database
        property: PASSWORD
    - secretKey: SPRING_MAIL_USERNAME
      remoteRef:
        key: /oficina/prod/mail
        property: USERNAME
    - secretKey: SPRING_MAIL_PASSWORD
      remoteRef:
        key: /oficina/prod/mail
        property: PASSWORD
