apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina
resources:
  - ../../base
patchesStrategicMerge:
  - configmap-patch.yaml
  - secret-patch.yaml
  - postgres-deployment-delete.yaml
  - postgres-pvc-delete.yaml
  - postgres-service-delete.yaml
images:
  - name: oficina
    newName: oficina
    newTag: latest
