apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: oficina-app
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
